const C=window.ADELUUVE_CONFIG||{};const URL=String(C.SUPABASE_URL||'').trim(),KEY=String(C.SUPABASE_KEY||'').trim();const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]));const sb=URL&&KEY&&!URL.includes('PEGA_AQUI')&&window.supabase?window.supabase.createClient(URL.replace(/\/+$/,''),KEY):null;
let contacts=[],projects=[],currentContact=null,currentProject=null,currentImages=[];
const loginScreen=$('#login-screen'),adminShell=$('#admin-shell'),loginForm=$('#login-form'),loginStatus=$('#login-status'),adminEmail=$('#admin-email');
function msg(el,text,ok=false){if(!el)return;el.textContent=text;el.style.color=ok?'#2f7d45':'#b44747'}
async function verifyAdmin(user){if(!sb||!user)return false;const {data,error}=await sb.from('administradores').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function setSession(session){if(!session?.user){loginScreen.classList.remove('hidden');adminShell.classList.add('hidden');return}const allowed=await verifyAdmin(session.user);if(!allowed){await sb.auth.signOut();msg(loginStatus,'Esta cuenta no está autorizada como administradora.');return}loginScreen.classList.add('hidden');adminShell.classList.remove('hidden');adminEmail.textContent=session.user.email||'';await refreshAll()}
loginForm?.addEventListener('submit',async e=>{e.preventDefault();if(!sb){msg(loginStatus,'Configura Supabase en ../config.js');return}msg(loginStatus,'');const email=$('#login-email').value.trim(),password=$('#login-password').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){msg(loginStatus,error.message);return}await setSession(data.session)});$('#logout-btn')?.addEventListener('click',async()=>{await sb?.auth.signOut();location.reload()});
$$('.side-link').forEach(btn=>btn.addEventListener('click',()=>{$$('.side-link').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${btn.dataset.view}`)?.classList.add('active');$('#view-title').textContent=btn.textContent.trim()}));
async function loadContacts(){const {data,error}=await sb.from('contactos').select('*').order('created_at',{ascending:false});if(error)throw error;contacts=data||[];renderContacts();renderRecent();updateMetrics()}
async function loadProjects(){const {data,error}=await sb.from('proyectos').select('*').order('created_at',{ascending:false});if(error)throw error;projects=data||[];renderProjects();updateMetrics()}
async function refreshAll(){try{await Promise.all([loadContacts(),loadProjects()])}catch(e){console.error(e)}}
function updateMetrics(){const count=s=>contacts.filter(c=>c.estatus===s).length;$('#metric-new').textContent=count('Nuevo');$('#metric-follow').textContent=count('En seguimiento');$('#metric-done').textContent=count('Finalizado');$('#metric-projects').textContent=projects.filter(p=>p.publicado).length}
function renderRecent(){const box=$('#recent-contacts');const items=contacts.slice(0,6);box.innerHTML=items.length?items.map(c=>`<article class="mini-contact"><div><h3>${esc(c.nombre||'Sin nombre')}</h3><p>${esc(c.servicio||'Sin servicio')} · ${new Date(c.created_at).toLocaleString('es-MX')}</p></div><span class="status-pill">${esc(c.estatus||'Nuevo')}</span></article>`).join(''):'<div class="empty">Sin solicitudes.</div>'}
const contactFilter=$('#contact-filter');contactFilter?.addEventListener('change',renderContacts);function renderContacts(){const box=$('#admin-contacts');const f=contactFilter?.value||'todos';const items=f==='todos'?contacts:contacts.filter(c=>c.estatus===f);box.innerHTML=items.length?items.map(c=>`<article class="contact-row" data-id="${c.id}"><div><h3>${esc(c.nombre||'Sin nombre')}</h3><p>${esc(c.empresa||'')} ${c.servicio?`· ${esc(c.servicio)}`:''}</p></div><span class="status-pill">${esc(c.estatus||'Nuevo')}</span></article>`).join(''):'<div class="empty">Sin solicitudes en este estado.</div>';$$('.contact-row',box).forEach(el=>el.addEventListener('click',()=>openContact(Number(el.dataset.id))))}
const contactDrawer=$('#contact-drawer');function closeContact(){contactDrawer.classList.remove('open');contactDrawer.setAttribute('aria-hidden','true')}$('#contact-drawer-close')?.addEventListener('click',closeContact);contactDrawer?.addEventListener('click',e=>{if(e.target===contactDrawer)closeContact()});function openContact(id){currentContact=contacts.find(c=>Number(c.id)===id);if(!currentContact)return;$('#contact-detail-name').textContent=currentContact.nombre||'Solicitud';$('#contact-status').value=currentContact.estatus||'Nuevo';const fields=[['Empresa',currentContact.empresa],['Correo',currentContact.correo],['Teléfono / WhatsApp',currentContact.telefono],['Servicio',currentContact.servicio],['Mensaje',currentContact.mensaje],['Fecha',new Date(currentContact.created_at).toLocaleString('es-MX')]];$('#contact-detail').innerHTML=fields.filter(([,v])=>v).map(([k,v])=>`<div class="detail-item"><b>${esc(k)}</b><span>${esc(v)}</span></div>`).join('');contactDrawer.classList.add('open');contactDrawer.setAttribute('aria-hidden','false')}
$('#save-contact-status')?.addEventListener('click',async()=>{if(!currentContact)return;const status=$('#contact-status').value;const out=$('#contact-detail-status');msg(out,'Guardando...',true);const {error}=await sb.from('contactos').update({estatus:status}).eq('id',currentContact.id);if(error){msg(out,error.message);return}currentContact.estatus=status;msg(out,'Estatus actualizado.',true);await loadContacts()});
function renderProjects(){const box=$('#admin-projects');box.innerHTML=projects.length?projects.map(p=>`<article class="admin-project"><div class="admin-project-media">${p.imagen_url?`<img src="${esc(p.imagen_url)}" alt="${esc(p.titulo||'Proyecto')}" loading="lazy" />`:''}</div><div class="admin-project-body"><h3>${esc(p.titulo||'Sin título')}</h3><p>${esc(p.descripcion||'')}</p><div class="project-actions"><button data-edit="${p.id}">Editar</button><button data-toggle="${p.id}">${p.publicado?'Ocultar':'Publicar'}</button><button class="danger" data-delete="${p.id}">Eliminar</button></div></div></article>`).join(''):'<div class="empty">Aún no hay proyectos.</div>';$$('[data-edit]',box).forEach(b=>b.addEventListener('click',()=>openProject(Number(b.dataset.edit))));$$('[data-toggle]',box).forEach(b=>b.addEventListener('click',()=>toggleProject(Number(b.dataset.toggle))));$$('[data-delete]',box).forEach(b=>b.addEventListener('click',()=>deleteProject(Number(b.dataset.delete))))}
const projectDrawer=$('#project-drawer'),projectForm=$('#project-form'),projectStatus=$('#project-form-status');$('#new-project-btn')?.addEventListener('click',()=>openProject(null));$('#project-drawer-close')?.addEventListener('click',closeProject);projectDrawer?.addEventListener('click',e=>{if(e.target===projectDrawer)closeProject()});function closeProject(){projectDrawer.classList.remove('open');projectDrawer.setAttribute('aria-hidden','true');projectForm.reset();currentProject=null;currentImages=[]}
async function loadProjectImages(id){const {data,error}=await sb.from('proyecto_imagenes').select('*').eq('proyecto_id',id).order('orden',{ascending:true}).order('created_at',{ascending:true});if(error){console.info(error.message);return[]}return data||[]}
async function openProject(id){currentProject=id?projects.find(p=>Number(p.id)===id):null;$('#project-form-title').textContent=currentProject?'Editar publicación':'Nueva publicación';$('#project-id').value=currentProject?.id||'';$('#project-title').value=currentProject?.titulo||'';$('#project-type').value=currentProject?.tipo||'Proyecto';$('#project-description').value=currentProject?.descripcion||'';$('#project-published').checked=currentProject?!!currentProject.publicado:true;currentImages=currentProject?await loadProjectImages(currentProject.id):[];renderExistingImages();msg(projectStatus,'');projectDrawer.classList.add('open');projectDrawer.setAttribute('aria-hidden','false')}
function renderExistingImages(){const box=$('#existing-images');const items=[];if(currentProject?.imagen_url)items.push({id:'main',imagen_url:currentProject.imagen_url,main:true});currentImages.forEach(i=>items.push({...i,main:false}));box.innerHTML=items.map(i=>`<div class="existing-image"><img src="${esc(i.imagen_url)}" alt="Imagen"/><button type="button" data-remove-image="${esc(i.id)}" data-main="${i.main?'1':'0'}">×</button></div>`).join('');$$('[data-remove-image]',box).forEach(b=>b.addEventListener('click',()=>removeImage(b.dataset.removeImage,b.dataset.main==='1')))}
async function uploadFiles(files,projectId){const urls=[];for(const file of files){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${projectId}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('proyectos').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;const {data}=sb.storage.from('proyectos').getPublicUrl(path);if(data?.publicUrl)urls.push(data.publicUrl)}return urls}
projectForm?.addEventListener('submit',async e=>{e.preventDefault();const title=$('#project-title').value.trim();if(!title){msg(projectStatus,'El título es obligatorio.');return}const payload={titulo:title,tipo:$('#project-type').value,descripcion:$('#project-description').value.trim()||null,publicado:$('#project-published').checked};const btn=$('#save-project-btn');btn.disabled=true;msg(projectStatus,'Guardando...',true);try{let id=currentProject?.id;if(id){const {error}=await sb.from('proyectos').update(payload).eq('id',id);if(error)throw error}else{const {data,error}=await sb.from('proyectos').insert([payload]).select('*').single();if(error)throw error;id=data.id;currentProject=data}const files=[...$('#project-images').files];if(files.length){const urls=await uploadFiles(files,id);if(urls.length){const existingMain=currentProject?.imagen_url;if(!existingMain){const main=urls.shift();const {error}=await sb.from('proyectos').update({imagen_url:main}).eq('id',id);if(error)throw error}if(urls.length){const {error}=await sb.from('proyecto_imagenes').insert(urls.map((u,i)=>({proyecto_id:id,imagen_url:u,orden:i+1})));if(error)throw error}}}msg(projectStatus,'Publicación guardada.',true);await loadProjects();setTimeout(closeProject,500)}catch(err){console.error(err);msg(projectStatus,err.message||'No fue posible guardar.')}finally{btn.disabled=false}});
async function toggleProject(id){const p=projects.find(x=>Number(x.id)===id);if(!p)return;const {error}=await sb.from('proyectos').update({publicado:!p.publicado}).eq('id',id);if(error)return alert(error.message);await loadProjects()}
async function deleteProject(id){if(!confirm('¿Eliminar esta publicación y sus imágenes relacionadas?'))return;const {error}=await sb.from('proyectos').delete().eq('id',id);if(error)return alert(error.message);await loadProjects()}
async function removeImage(id,isMain){if(!currentProject)return;if(isMain){const {error}=await sb.from('proyectos').update({imagen_url:null}).eq('id',currentProject.id);if(error)return msg(projectStatus,error.message);currentProject.imagen_url=null}else{const {error}=await sb.from('proyecto_imagenes').delete().eq('id',id);if(error)return msg(projectStatus,error.message);currentImages=currentImages.filter(i=>String(i.id)!==String(id))}renderExistingImages();msg(projectStatus,'Imagen retirada de la publicación.',true)}
(async()=>{if(!sb){msg(loginStatus,'Configura Supabase en ../config.js');return}const {data}=await sb.auth.getSession();await setSession(data.session);sb.auth.onAuthStateChange((_e,session)=>{if(!session)location.reload()})})();
