const CFG = window.ADELUUVE_CONFIG || {};
const SUPABASE_URL = String(CFG.SUPABASE_URL || "").trim();
const SUPABASE_KEY = String(CFG.SUPABASE_KEY || "").trim();
const CONTACT = CFG.CONTACT || {};
const $ = (s,c=document)=>c.querySelector(s); const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const normalize=v=>String(v??"").trim();
const escapeHtml=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]));
function safeUrl(v=""){try{const u=new URL(v);return ["https:","http:"].includes(u.protocol)?u.href:""}catch{return ""}}
const isSupabaseConfigured=SUPABASE_URL&&SUPABASE_KEY&&!SUPABASE_URL.includes("PEGA_AQUI")&&!SUPABASE_KEY.includes("PEGA_AQUI");
const supabaseClient=isSupabaseConfigured&&window.supabase?window.supabase.createClient(SUPABASE_URL.replace(/\/+$/, ""),SUPABASE_KEY):null;

const header=$(".site-header"),menuBtn=$(".menu-toggle"),nav=$(".nav"),progressBar=$("#page-progress");
menuBtn?.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});
$$('.nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false')}));
function updateScrollUI(){const y=window.scrollY;header?.classList.toggle('scrolled',y>12);if(progressBar){const max=document.documentElement.scrollHeight-window.innerHeight;progressBar.style.width=`${max>0?Math.min(100,Math.max(0,(y/max)*100)):0}%`}}
window.addEventListener('scroll',updateScrollUI,{passive:true});updateScrollUI();

const revealObserver='IntersectionObserver'in window?new IntersectionObserver((entries,observer)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -30px 0px'}):null;
function observeReveals(ctx=document){$$('.reveal',ctx).forEach(el=>{if(el.classList.contains('visible'))return;revealObserver?revealObserver.observe(el):el.classList.add('visible')})}observeReveals();
const methodology=$("#metodologia"),trackProgress=$("#track-progress");if(methodology&&trackProgress&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){trackProgress.style.width='100%';io.disconnect()}},{threshold:.35});io.observe(methodology)}
const navLinks=$$(".nav a[href^='#']").filter(a=>!a.classList.contains('nav-cta')),sections=navLinks.map(a=>$(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window&&sections.length){const io=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${visible.target.id}`))},{threshold:[.25,.45,.65],rootMargin:'-20% 0px -55% 0px'});sections.forEach(s=>io.observe(s))}
const year=$("#year");if(year)year.textContent=new Date().getFullYear();

const contactData=$("#contact-data");const contactItems=[["Tel. / WhatsApp",CONTACT.phone],["Correo",CONTACT.email],["Ubicación / cobertura",CONTACT.location]].filter(([,v])=>normalize(v));if(contactData)contactData.innerHTML=contactItems.map(([l,v])=>`<div class="contact-item"><b>${escapeHtml(l)}:</b><span>${escapeHtml(v)}</span></div>`).join('');

const contactForm=$("#contact-form"),formStatus=$("#form-status"),submitButton=$("#submit-contact");
function setFormStatus(msg,type=''){if(!formStatus)return;formStatus.textContent=msg;formStatus.classList.remove('success','error');if(type)formStatus.classList.add(type)}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
contactForm?.addEventListener('submit',async e=>{e.preventDefault();$$('input,textarea,select',contactForm).forEach(el=>el.classList.remove('invalid'));const fd=new FormData(contactForm);if(normalize(fd.get('sitio_web'))){contactForm.reset();setFormStatus('Solicitud enviada correctamente.','success');return}
  const payload={nombre:normalize(fd.get('nombre')),empresa:normalize(fd.get('empresa'))||null,correo:normalize(fd.get('correo')),telefono:normalize(fd.get('telefono'))||null,servicio:normalize(fd.get('servicio'))||null,mensaje:normalize(fd.get('mensaje')),estatus:'Nuevo'};
  const invalid=[];if(!payload.nombre)invalid.push('[name="nombre"]');if(!payload.correo||!validEmail(payload.correo))invalid.push('[name="correo"]');if(!payload.mensaje)invalid.push('[name="mensaje"]');invalid.forEach(s=>$(s,contactForm)?.classList.add('invalid'));if(invalid.length){setFormStatus('Revisa nombre, correo y descripción antes de enviar.','error');return}
  if(!supabaseClient){setFormStatus('El formulario todavía no está conectado. Revisa config.js.','error');console.error('Supabase no configurado');return}
  submitButton.disabled=true;submitButton.querySelector('span').textContent='Enviando...';setFormStatus('Enviando solicitud...');
  try{const {data,error}=await supabaseClient.from('contactos').insert([payload]).select('id').single();if(error)throw error;contactForm.reset();setFormStatus(data?.id?`Solicitud enviada correctamente. Folio ${data.id}.`:'Solicitud enviada correctamente. Gracias por contactar a ADELUUVE.','success')}
  catch(err){console.error('Error al guardar el contacto:',err);setFormStatus('No fue posible enviar la solicitud. Intenta nuevamente en unos momentos.','error')}
  finally{submitButton.disabled=false;submitButton.querySelector('span').textContent='Enviar solicitud'}
});

const projectsGrid=$("#projects-grid"),projectFilters=$$('.project-filter');let allProjects=[],activeFilter='todos';
async function attachProjectImages(projects){if(!supabaseClient||!projects.length)return projects.map(p=>({...p,imagenes:safeUrl(p.imagen_url)?[safeUrl(p.imagen_url)]:[]}));try{const ids=projects.map(p=>p.id).filter(Boolean);const {data,error}=await supabaseClient.from('proyecto_imagenes').select('id,proyecto_id,imagen_url,orden,created_at').in('proyecto_id',ids).order('orden',{ascending:true}).order('created_at',{ascending:true});if(error)throw error;const grouped=new Map();(data||[]).forEach(img=>{const url=safeUrl(img.imagen_url);if(!url)return;if(!grouped.has(img.proyecto_id))grouped.set(img.proyecto_id,[]);grouped.get(img.proyecto_id).push(url)});return projects.map(p=>({...p,imagenes:[...new Set([safeUrl(p.imagen_url),...(grouped.get(p.id)||[])].filter(Boolean))]}))}catch(err){console.info('proyecto_imagenes no disponible:',err?.message||err);return projects.map(p=>({...p,imagenes:safeUrl(p.imagen_url)?[safeUrl(p.imagen_url)]:[]}))}}
function filteredProjects(){return activeFilter==='todos'?allProjects:allProjects.filter(p=>normalize(p.tipo).toLowerCase()===activeFilter)}
function renderProjects(items){if(!projectsGrid)return;if(!items.length){projectsGrid.innerHTML='<div class="projects-empty">Todavía no hay proyectos publicados en esta categoría.</div>';return}projectsGrid.innerHTML=items.map((p,index)=>{const image=p.imagenes?.[0]||'',total=p.imagenes?.length||0,title=p.titulo||'Trabajo realizado',desc=p.descripcion||'',type=p.tipo||'Proyecto';return `<article class="project-card reveal" data-index="${index}" tabindex="0" role="button" aria-label="Ver ${escapeHtml(title)}">${image?`<img src="${escapeHtml(image)}" alt="${escapeHtml(title)}" loading="lazy" decoding="async" />`:'<div class="project-no-image">ADELUUVE</div>'}<span class="project-view">↗</span>${total>1?`<span class="project-photo-count">${total} fotos</span>`:''}<div class="project-card-copy"><span>${escapeHtml(type)}</span><h3>${escapeHtml(title)}</h3>${desc?`<p>${escapeHtml(desc)}</p>`:''}</div></article>`}).join('');observeReveals(projectsGrid);$$('.project-card',projectsGrid).forEach(card=>{const open=()=>openProjectModal(items[Number(card.dataset.index)]);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
async function loadProjects(){if(!projectsGrid)return;if(!supabaseClient){projectsGrid.innerHTML='<div class="projects-empty">Configura Supabase en config.js para mostrar tus trabajos y proyectos.</div>';return}try{const {data,error}=await supabaseClient.from('proyectos').select('id,titulo,descripcion,imagen_url,tipo,publicado,created_at').eq('publicado',true).order('created_at',{ascending:false});if(error)throw error;allProjects=await attachProjectImages(data||[]);renderProjects(filteredProjects())}catch(err){console.error('Error al cargar proyectos:',err);projectsGrid.innerHTML='<div class="projects-empty">No fue posible cargar los proyectos en este momento.</div>'}}
projectFilters.forEach(btn=>btn.addEventListener('click',()=>{projectFilters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter||'todos';renderProjects(filteredProjects())}));

const modal=$("#project-modal"),modalClose=$("#project-modal-close"),modalPrev=$("#project-modal-prev"),modalNext=$("#project-modal-next"),modalCounter=$("#project-modal-counter"),modalImage=$("#project-modal-image"),thumbs=$("#project-thumbs");let currentImages=[],imageIndex=0,lastFocus=null;
function renderThumbs(){if(!thumbs)return;thumbs.innerHTML=currentImages.map((src,i)=>`<button class="project-thumb ${i===imageIndex?'active':''}" type="button" data-i="${i}" aria-label="Ver imagen ${i+1}"><img src="${escapeHtml(src)}" alt="Miniatura ${i+1}" loading="lazy" /></button>`).join('');$$('.project-thumb',thumbs).forEach(b=>b.addEventListener('click',()=>{imageIndex=Number(b.dataset.i);updateModalImage()}))}
function updateModalImage(){if(!modalImage)return;modalImage.classList.add('changing');setTimeout(()=>{modalImage.src=currentImages[imageIndex]||'';modalImage.classList.remove('changing')},90);const multiple=currentImages.length>1;modalPrev?.classList.toggle('show',multiple);modalNext?.classList.toggle('show',multiple);if(modalCounter)modalCounter.textContent=multiple?`${imageIndex+1} / ${currentImages.length}`:'';renderThumbs()}
function openProjectModal(p){if(!modal||!p)return;lastFocus=document.activeElement;currentImages=p.imagenes?.length?p.imagenes:(safeUrl(p.imagen_url)?[safeUrl(p.imagen_url)]:[]);imageIndex=0;if(modalImage)modalImage.alt=p.titulo||'Proyecto ADELUUVE';$("#project-modal-type").textContent=p.tipo||'Proyecto';$("#project-modal-title").textContent=p.titulo||'Trabajo realizado';$("#project-modal-description").textContent=p.descripcion||'';updateModalImage();modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modalClose?.focus()}
function closeModal(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');lastFocus?.focus?.()}
function stepImage(dir){if(currentImages.length<2)return;imageIndex=(imageIndex+dir+currentImages.length)%currentImages.length;updateModalImage()}
modalPrev?.addEventListener('click',e=>{e.stopPropagation();stepImage(-1)});modalNext?.addEventListener('click',e=>{e.stopPropagation();stepImage(1)});modalClose?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(!modal?.classList.contains('open'))return;if(e.key==='Escape')closeModal();if(e.key==='ArrowLeft')stepImage(-1);if(e.key==='ArrowRight')stepImage(1)});let touchStartX=0;modal?.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0]?.screenX||0},{passive:true});modal?.addEventListener('touchend',e=>{const diff=(e.changedTouches[0]?.screenX||0)-touchStartX;if(Math.abs(diff)>55)stepImage(diff>0?-1:1)},{passive:true});
loadProjects();
