-- ============================================================
-- ADELUUVE — CONFIGURACIÓN DE SUPABASE
-- Ejecuta este archivo en SQL Editor.
-- Está diseñado para conservar las tablas actuales si ya existen.
-- ============================================================

create table if not exists public.contactos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text not null,
  empresa text,
  correo text not null,
  telefono text,
  servicio text,
  mensaje text not null,
  estatus text not null default 'Nuevo'
);

create table if not exists public.proyectos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  titulo text not null,
  descripcion text,
  imagen_url text,
  tipo text default 'Proyecto',
  publicado boolean not null default true
);

create table if not exists public.proyecto_imagenes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  proyecto_id bigint not null references public.proyectos(id) on delete cascade,
  imagen_url text not null,
  orden integer default 0
);

-- Guarda los usuarios de Supabase Auth autorizados para /admin.
create table if not exists public.administradores (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.contactos enable row level security;
alter table public.proyectos enable row level security;
alter table public.proyecto_imagenes enable row level security;
alter table public.administradores enable row level security;

-- Función segura para verificar si la sesión pertenece a un administrador.
create or replace function public.es_administrador()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.administradores
    where user_id = auth.uid()
  );
$$;

revoke all on function public.es_administrador() from public;
grant execute on function public.es_administrador() to anon, authenticated;

-- Limpiar únicamente las policies de este paquete para poder re-ejecutarlo.
drop policy if exists "web_publica_inserta_contactos" on public.contactos;
drop policy if exists "admin_lee_contactos" on public.contactos;
drop policy if exists "admin_actualiza_contactos" on public.contactos;
drop policy if exists "admin_elimina_contactos" on public.contactos;

drop policy if exists "web_publica_lee_proyectos" on public.proyectos;
drop policy if exists "admin_lee_proyectos" on public.proyectos;
drop policy if exists "admin_inserta_proyectos" on public.proyectos;
drop policy if exists "admin_actualiza_proyectos" on public.proyectos;
drop policy if exists "admin_elimina_proyectos" on public.proyectos;

drop policy if exists "web_publica_lee_imagenes" on public.proyecto_imagenes;
drop policy if exists "admin_lee_imagenes" on public.proyecto_imagenes;
drop policy if exists "admin_inserta_imagenes" on public.proyecto_imagenes;
drop policy if exists "admin_actualiza_imagenes" on public.proyecto_imagenes;
drop policy if exists "admin_elimina_imagenes" on public.proyecto_imagenes;

drop policy if exists "admin_lee_su_registro" on public.administradores;

create policy "web_publica_inserta_contactos"
on public.contactos for insert
to anon
with check (true);

create policy "admin_lee_contactos"
on public.contactos for select
to authenticated
using (public.es_administrador());

create policy "admin_actualiza_contactos"
on public.contactos for update
to authenticated
using (public.es_administrador())
with check (public.es_administrador());

create policy "admin_elimina_contactos"
on public.contactos for delete
to authenticated
using (public.es_administrador());

create policy "web_publica_lee_proyectos"
on public.proyectos for select
to anon, authenticated
using (publicado = true or public.es_administrador());

create policy "admin_lee_proyectos"
on public.proyectos for select
to authenticated
using (public.es_administrador());

create policy "admin_inserta_proyectos"
on public.proyectos for insert
to authenticated
with check (public.es_administrador());

create policy "admin_actualiza_proyectos"
on public.proyectos for update
to authenticated
using (public.es_administrador())
with check (public.es_administrador());

create policy "admin_elimina_proyectos"
on public.proyectos for delete
to authenticated
using (public.es_administrador());

create policy "web_publica_lee_imagenes"
on public.proyecto_imagenes for select
to anon, authenticated
using (
  exists (
    select 1 from public.proyectos p
    where p.id = proyecto_id
      and (p.publicado = true or public.es_administrador())
  )
);

create policy "admin_lee_imagenes"
on public.proyecto_imagenes for select
to authenticated
using (public.es_administrador());

create policy "admin_inserta_imagenes"
on public.proyecto_imagenes for insert
to authenticated
with check (public.es_administrador());

create policy "admin_actualiza_imagenes"
on public.proyecto_imagenes for update
to authenticated
using (public.es_administrador())
with check (public.es_administrador());

create policy "admin_elimina_imagenes"
on public.proyecto_imagenes for delete
to authenticated
using (public.es_administrador());

create policy "admin_lee_su_registro"
on public.administradores for select
to authenticated
using (auth.uid() = user_id);

-- Bucket público para las imágenes de proyectos.
insert into storage.buckets (id, name, public)
values ('proyectos', 'proyectos', true)
on conflict (id) do update set public = true;

-- Policies de Storage.
drop policy if exists "publico_lee_proyectos_storage" on storage.objects;
drop policy if exists "admin_inserta_proyectos_storage" on storage.objects;
drop policy if exists "admin_actualiza_proyectos_storage" on storage.objects;
drop policy if exists "admin_elimina_proyectos_storage" on storage.objects;

create policy "publico_lee_proyectos_storage"
on storage.objects for select
to public
using (bucket_id = 'proyectos');

create policy "admin_inserta_proyectos_storage"
on storage.objects for insert
to authenticated
with check (bucket_id = 'proyectos' and public.es_administrador());

create policy "admin_actualiza_proyectos_storage"
on storage.objects for update
to authenticated
using (bucket_id = 'proyectos' and public.es_administrador())
with check (bucket_id = 'proyectos' and public.es_administrador());

create policy "admin_elimina_proyectos_storage"
on storage.objects for delete
to authenticated
using (bucket_id = 'proyectos' and public.es_administrador());

-- IMPORTANTE:
-- 1) Crea el usuario administrador en Authentication > Users.
-- 2) Copia su UUID.
-- 3) Ejecuta, sustituyendo TU_UUID:
-- insert into public.administradores(user_id) values ('TU_UUID');
